set smartindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set ignorecase
set gdefault
set magic
set incsearch
set hlsearch
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent
set nowrap
set modeline
set splitbelow
set splitright
set nostartofline
set nobackup
set noswapfile
set showmatch
set wrapscan
set mouse=a

set wildignore+=tmp/*,.tmp/*,dist/*,.dist/*
set wildignore+=*.so,*.swp,*.zip
set wildignore+=*/node_modules,*/vendor
